/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Alert */
        post: operations["acknowledge_alert_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Alert */
        post: operations["resolve_alert_v1_alerts__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Capture */
        post: operations["create_capture_v1_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capture */
        get: operations["capture_v1_captures__capture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures/{capture_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Capture */
        post: operations["complete_capture_v1_captures__capture_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures/{capture_id}/refresh-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Capture Uploads */
        post: operations["refresh_capture_uploads_v1_captures__capture_id__refresh_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures/{capture_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Capture */
        post: operations["retry_capture_v1_captures__capture_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facilities */
        get: operations["facilities_v1_facilities_get"];
        put?: never;
        /** Create Facility */
        post: operations["create_facility_v1_facilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facilities/{facility_id}/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stations */
        get: operations["stations_v1_facilities__facility_id__stations_get"];
        put?: never;
        /** Create Station */
        post: operations["create_station_v1_facilities__facility_id__stations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations */
        get: operations["observations_v1_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation */
        get: operations["observation_v1_observations__observation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}/delete-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Observation Media */
        post: operations["delete_observation_media_v1_observations__observation_id__delete_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Observation */
        post: operations["review_observation_v1_observations__observation_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registrations */
        get: operations["registrations_v1_registrations_get"];
        put?: never;
        /** Create Registration */
        post: operations["create_registration_v1_registrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registrations/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Registration */
        delete: operations["delete_registration_v1_registrations__registration_id__delete"];
        options?: never;
        head?: never;
        /** Patch Registration */
        patch: operations["patch_registration_v1_registrations__registration_id__patch"];
        trace?: never;
    };
    "/v1/stations/{station_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Station Heartbeat */
        post: operations["station_heartbeat_v1_stations__station_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dlq */
        get: operations["dlq_v1_system_dlq_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/dlq/{message_id}/redrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redrive Dlq */
        post: operations["redrive_dlq_v1_system_dlq__message_id__redrive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Health */
        get: operations["system_health_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Time */
        get: operations["get_time_v1_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visits */
        get: operations["visits_v1_visits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/visits/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Visits */
        get: operations["open_visits_v1_visits_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visit */
        get: operations["visit_v1_visits__visit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaptureComplete */
        CaptureComplete: {
            /** Uploadedkeys */
            uploadedKeys: string[];
        };
        /** CaptureCreate */
        CaptureCreate: {
            /**
             * Capturedatclient
             * Format: date-time
             */
            capturedAtClient: string;
            /** Clientclockoffsetms */
            clientClockOffsetMs: number;
            /** Facilityid */
            facilityId: string;
            /** Framecount */
            frameCount: number;
            guideRegion?: components["schemas"]["NormalizedRegion"] | null;
            /** Stationid */
            stationId: string;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
        };
        /** CaptureCreated */
        CaptureCreated: {
            /** Captureid */
            captureId: string;
            /** Correlationid */
            correlationId: string;
            /**
             * Estimatedcapturedatserver
             * Format: date-time
             */
            estimatedCapturedAtServer: string;
            /**
             * Receivedatserver
             * Format: date-time
             */
            receivedAtServer: string;
            /**
             * Status
             * @constant
             */
            status: "UPLOADING";
            /** Uploads */
            uploads: components["schemas"]["PresignedFrame"][];
        };
        /** CaptureUploadsRefreshed */
        CaptureUploadsRefreshed: {
            /** Captureid */
            captureId: string;
            /**
             * Status
             * @constant
             */
            status: "UPLOADING";
            /** Uploads */
            uploads: components["schemas"]["PresignedFrame"][];
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "ENTRY" | "EXIT";
        /** FacilityCreate */
        FacilityCreate: {
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            /** Armed */
            armed: boolean;
            /** Camera Device Hash */
            camera_device_hash?: string | null;
            /**
             * Client Time
             * Format: date-time
             */
            client_time: string;
        };
        /** NormalizedRegion */
        NormalizedRegion: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ObservationReview */
        ObservationReview: {
            /** Correctedplate */
            correctedPlate?: string | null;
            decision: components["schemas"]["ReviewDecision"];
            /** Note */
            note: string;
        };
        /** Page */
        Page: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** PresignedFrame */
        PresignedFrame: {
            /** Expiresin */
            expiresIn: number;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Frameindex */
            frameIndex: number;
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
        /** RegistrationCreate */
        RegistrationCreate: {
            /** Description */
            description?: string | null;
            /** Displayplate */
            displayPlate: string;
            /** Facilityid */
            facilityId?: string | null;
            /** Normalizedplate */
            normalizedPlate: string;
            /** Plateregion */
            plateRegion?: string | null;
            /** @default ACTIVE */
            status: components["schemas"]["RegistrationStatus"];
            /**
             * Validfrom
             * Format: date-time
             */
            validFrom: string;
            /** Validuntil */
            validUntil?: string | null;
        };
        /** RegistrationPatch */
        RegistrationPatch: {
            /** Description */
            description?: string | null;
            /** Displayplate */
            displayPlate?: string | null;
            /** Plateregion */
            plateRegion?: string | null;
            status?: components["schemas"]["RegistrationStatus"] | null;
            /** Validuntil */
            validUntil?: string | null;
        };
        /**
         * RegistrationStatus
         * @enum {string}
         */
        RegistrationStatus: "ACTIVE" | "EXPIRED" | "BLOCKED";
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "CONFIRMED" | "CORRECTED" | "REJECTED";
        /** StationCreate */
        StationCreate: {
            /**
             * Cooldown Seconds
             * @default 15
             */
            cooldown_seconds: number;
            direction: components["schemas"]["Direction"];
            /**
             * Motion Sensitivity
             * @default 0.12
             */
            motion_sensitivity: number;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_v1_alerts_get: {
        parameters: {
            query: {
                facilityId: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_v1_alerts__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capture_v1_captures_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_v1_captures__capture_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_capture_v1_captures__capture_id__complete_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_capture_uploads_v1_captures__capture_id__refresh_uploads_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureUploadsRefreshed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_capture_v1_captures__capture_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facilities_v1_facilities_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_facility_v1_facilities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stations_v1_facilities__facility_id__stations_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_station_v1_facilities__facility_id__stations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observations_v1_observations_get: {
        parameters: {
            query: {
                facilityId: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_v1_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_observation_media_v1_observations__observation_id__delete_media_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_observation_v1_observations__observation_id__review_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrations_v1_registrations_get: {
        parameters: {
            query: {
                facilityId: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_registration_v1_registrations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_registration_v1_registrations__registration_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_registration_v1_registrations__registration_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    station_heartbeat_v1_stations__station_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dlq_v1_system_dlq_get: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redrive_dlq_v1_system_dlq__message_id__redrive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_health_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_time_v1_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    visits_v1_visits_get: {
        parameters: {
            query: {
                facilityId: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_visits_v1_visits_open_get: {
        parameters: {
            query: {
                facilityId: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visit_v1_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-gatesight-dev-claims"?: string | null;
            };
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
